li = ['wo', 'shi', 'hao', 'ren']
st = ['cheng', 'long']
print(li, "\n", st)
li.append('!')
print(li)
print(li.count('wo'))
li.extend(st)
print(li)
print(li.index('shi'))
li.insert(2, 'yi ge')
print(li)
li.pop(5)
print(li)
li.remove('yi ge')
print(li)
li.reverse()
print(li)
li.sort()
print(li)
st.copy()
print(st)
li.clear()
print(li)